#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cd $OPENSHIFT_REPO_DIR

# Fix the problem of jekyll-press with non-English language
export LANG=ru_RU.UTF-8

bundle exec jekyll build
