image: ruby:2.5-alpine

variables:
  JEKYLL_ENV: production
  LC_ALL: en_US.UTF-8

build site:
  stage: build
  before_script:
    - apk add --no-cache g++ musl-dev make
    - apk add --no-cache libstdc++
    - bundle install --path=vendor/
  script:
  - bundle exec jekyll build -d lorchess.ru
  artifacts:
    untracked: true
    expire_in: 4 hours
    paths:
      - lorchess.ru

deploy site:
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SSH_HOST >> ~/.ssh/known_hosts
  script:
    - scp -r lorchess.ru $DEPLOY_SSH_USER@$DEPLOY_SSH_HOST:$DEPLOY_PATH