image: ruby:2.5-alpine

variables:
  JEKYLL_ENV: production
  LC_ALL: en_US.UTF-8

before_script:
  - apk add --no-cache g++ musl-dev make
  - apk add --no-cache libstdc++
  - bundle install --path=vendor/

build site:
  stage: build
  script:
  - ls ./
  - bundle exec jekyll build -d public
  artifacts:
    expire_in: 1 month
    paths:
    - public
