url:       http://lorchess.ru
title:     LORChess
permalink: pretty

destination: public
exclude:     ['assets/vendor', 'Gemfile*', 'Guardfile', 'README*', 'vendor']
keep_files:  ['.gitkeep']
plugins: ['jekyll-assets']

encoding: UTF-8

# Collect SCSS files into a collection to suppress them from being
# added to Jekyll::Page
collections:
  scss:
    output:    true
    permalink: /assets/css/:path.css

sass:
  style: :compressed
