url:       http://lorchess.ru
title:     LORChess
permalink: pretty

source:      ./
destination: ./public
exclude:     ['Gemfile*', 'Guardfile', 'README*', 'vendor']
keep_files:  ['.gitkeep']

encoding: UTF-8
markdown: kramdown
gems:     ['jekyll-assets']

#
# Plugin: jekyll-assets
#
assets:
  #
  # Sets compressors. No compression by default.
  #
  compress:
    js:  yui
    css: yui
